[package]
name = "kernel8"
version = "0.1.0"
authors = ["Sergey Cheung <sergeychang@gmail.com>"]
edition = "2018"

[dependencies]
raspi3_boot = { path = "raspi3_boot" }
cortex-a = "2.3.1"
register = "0.3.2"

[package.metadata.cargo-xbuild]
sysroot_path = "xbuild_sysroot"
